---
title: ""
date: 2015-11-08
author: Thao Nguyen
categories: [R]
output:
    html:
        highlight: haddock
        theme: journal
execute:
    echo: false
    message: false
    warning: false
---

```{r}
# load libraries
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(readr)
```

```{r}
##### read in data 
space <- read_csv(
  "data/space_missions_copy.csv", 
  locale = locale(encoding = "ISO-8859-1"), # need 'locale' argument due to some french text
  ) 
```

```{r}
##### pre-process data

# change column names
space_n <- clean_names(space)

# guess_encoding("data/space_missions_copy.csv")
  # guess the encoding of file so UTF-8 -> ISO-8859-1

# add year, month, and year_month columns for easier (?) data manipulation
space_n <- space_n |>
  mutate(
    year = year(mdy(date)),
    month = month(mdy(date)),
    year_month = format(mdy(date), "%Y-%m")
  )
```

```{r}
# 62 distinct space companies
space_n |>
  distinct(company)

# 16 distinct countries (not accounting for joint efforts)
space_n |>
  distinct(origin)

# number of rocket launches by country
  # russia > usa >> china > france 
space_n |>
  group_by(origin) |>
  count(origin) |>
  arrange(desc(n))

# joint efforts by multiple countries
space_n |>
  filter(origin == 'Other') |>
  count(alternative_origin) |>
  arrange(desc(n))

# mission status
space_n |>
  group_by(mission_status) |>
  count() |>
  arrange(desc(n))

# rocket status
space_n |>
  group_by(rocket_status) |>
  count() |>
  arrange(desc(n))

# rocket launches by year
space_n |>
  group_by(year) |>
  count() |>
  ggplot(aes(x = year, y = n)) +
    geom_line()

# rocket launches by year by country
space_n |>
  group_by(year, origin) |>
  count() |>
  slice_max(order_by = n, n = 5) |>
  ggplot(aes(x = year, y = n, color = origin)) +
    geom_line()
```


